import {
  Student,
  PaymentReceipt,
  ExamApplication,
  InventoryItem,
  SupplySale,
  OperationItem,
  PriorityAlert,
  Agent,
  Tutor,
} from '../types';
import {
  db,
  doc,
  setDoc,
  getDocs,
  collection,
  sanitizeForFirestore,
  COLLECTIONS,
  OperationType,
  handleFirestoreError,
  safeFirestoreWrite,
} from './index';

// Initial dataset to seed Firestore on first connection
export const SEED_AGENTS: Agent[] = [
  {
    id: 'agent-1',
    username: 'admin',
    fullName: 'M. Lawali B.',
    gender: 'Masculin (M)',
    role: 'Administrateur Principal',
    email: 'MsLawali85@gmail.com',
    phone: '+227 96 00 11 22',
    campus: 'Campus Niamey Plateau (Central)',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    active: true,
  },
  {
    id: 'agent-2',
    username: 'hadiza.caisse',
    fullName: 'Hadiza Moussa',
    gender: 'Féminin (F)',
    role: 'Agent de Caisse',
    email: 'caisse.plateau@cabappuis.ne',
    phone: '+227 90 22 33 44',
    campus: 'Campus Niamey Plateau (Central)',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    active: true,
  },
  {
    id: 'agent-3',
    username: 'ousmane.pedago',
    fullName: 'Prof. Ousmane Adamou',
    gender: 'Masculin (M)',
    role: 'Responsable Pédagogique',
    email: 'pedago@cabappuis.ne',
    phone: '+227 94 33 44 55',
    campus: 'Campus Niamey Plateau (Central)',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    active: true,
  },
  {
    id: 'agent-4',
    username: 'fatima.secretariat',
    fullName: 'Fatima Salifou',
    gender: 'Féminin (F)',
    role: 'Secrétaire d\'Accueil',
    email: 'accueil.plateau@cabappuis.ne',
    phone: '+227 80 44 55 66',
    campus: 'Campus Niamey Plateau (Central)',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    active: true,
  },
];

export const SEED_TUTORS: Tutor[] = [
  {
    id: 'tutor-1',
    matricule: 'ENC-2026-001',
    fullName: 'Prof. Ousmane Adamou',
    gender: 'Masculin (M)',
    phone: '+227 94 33 44 55',
    email: 'ousmane.adamou@cabappuis.ne',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    subjects: ['Mathématiques', 'Physique-Chimie', 'Calcul & Problèmes'],
    levels: ['Primaire', 'Collège', 'Lycée', 'Supérieur'],
    assignedStudentIds: ['stu-1', 'stu-3', 'stu-4'],
    sessions: [],
    totalHours: 18,
    syncStatus: 'synced',
    agentId: 'agent-1',
    agentName: 'M. Lawali B.',
    agentRole: 'Administrateur Principal',
  },
  {
    id: 'tutor-2',
    matricule: 'ENC-2026-002',
    fullName: 'Mme Aminata Kaboré',
    gender: 'Féminin (F)',
    phone: '+227 97 88 12 34',
    email: 'aminata.kabore@cabappuis.ne',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    subjects: ['Français', 'Grammaire & Orthographe', 'Anglais'],
    levels: ['Primaire', 'Collège'],
    assignedStudentIds: ['stu-2', 'stu-4'],
    sessions: [],
    totalHours: 24,
    syncStatus: 'synced',
    agentId: 'agent-1',
    agentName: 'M. Lawali B.',
    agentRole: 'Administrateur Principal',
  },
];

export const SEED_STUDENTS: Student[] = [
  {
    id: 'stu-1',
    matricule: 'CAB-2026-0012',
    fullName: 'Hadiza Moussa Oumarou',
    level: 'CM2 (CFEPD & Entrée en 6ème)',
    stream: 'Primaire',
    subjects: ['Calcul & Problèmes', 'Grammaire & Orthographe', 'Étude du Milieu', 'Dictée'],
    guardianName: 'Elhadj Moussa Oumarou (Père)',
    guardianPhone: '+227 96 42 11 89',
    monthlyFee: 20000,
    paidAmount: 20000,
    paymentStatus: 'A jour',
    tutoringStatus: 'Actif',
    enrollmentDate: '10 Jan 2026',
    syncStatus: 'synced',
    notes: 'Préparation intensive au CFEPD - Quartier Yantala.',
    agentId: 'agent-1',
    agentName: 'M. Lawali B.',
    agentRole: 'Administrateur Principal',
  },
  {
    id: 'stu-2',
    matricule: 'CAB-2026-0034',
    fullName: 'Ibrahim Amadou Diallo',
    level: 'CE2',
    stream: 'Primaire',
    subjects: ['Lecture fluide', 'Écriture', 'Calcul rapide'],
    guardianName: 'Mme Fatima Amadou (Mère)',
    guardianPhone: '+227 90 15 88 44',
    monthlyFee: 18000,
    paidAmount: 18000,
    paymentStatus: 'A jour',
    tutoringStatus: 'Actif',
    enrollmentDate: '15 Jan 2026',
    syncStatus: 'synced',
    notes: 'Soutien aux fondamentaux en lecture et calcul - Quartier Koira Kano.',
    agentId: 'agent-4',
    agentName: 'Fatima Salifou',
    agentRole: 'Secrétaire d\'Accueil',
  },
  {
    id: 'stu-3',
    matricule: 'CAB-2026-0042',
    fullName: 'Abdoulaye Garba Souley',
    level: 'Terminale D (Bac Scientifique)',
    stream: 'Lycée',
    subjects: ['Mathématiques', 'Sciences Physiques', 'SVT'],
    guardianName: 'Dr. Garba Souley (Père)',
    guardianPhone: '+227 96 55 22 10',
    monthlyFee: 35000,
    paidAmount: 35000,
    paymentStatus: 'A jour',
    tutoringStatus: 'Actif',
    enrollmentDate: '18 Jan 2026',
    syncStatus: 'synced',
    notes: 'Candidat au Baccalauréat Série D - Lycée Kassaï / Plateau.',
    agentId: 'agent-1',
    agentName: 'M. Lawali B.',
    agentRole: 'Administrateur Principal',
  },
  {
    id: 'stu-4',
    matricule: 'CAB-2026-0089',
    fullName: 'Zeinabou Boubacar Maïga',
    level: 'Troisième 3ème (BEPC)',
    stream: 'Collège',
    subjects: ['Mathématiques', 'Français', 'Anglais', 'Physique-Chimie'],
    guardianName: 'M. Boubacar Maïga',
    guardianPhone: '+227 97 12 34 56',
    monthlyFee: 25000,
    paidAmount: 25000,
    paymentStatus: 'A jour',
    tutoringStatus: 'Actif',
    enrollmentDate: '20 Jan 2026',
    syncStatus: 'synced',
    notes: 'Objectif : Mention Très Bien au BEPC 2026.',
    agentId: 'agent-3',
    agentName: 'Prof. Ousmane Adamou',
    agentRole: 'Responsable Pédagogique',
  },
  {
    id: 'stu-5',
    matricule: 'CAB-2026-0105',
    fullName: 'Mahamadou Issoufou Salifou',
    level: 'Terminale C (Maths & Sciences)',
    stream: 'Lycée',
    subjects: ['Mathématiques approfondies', 'Physique-Chimie'],
    guardianName: 'Issoufou Salifou (Oncle)',
    guardianPhone: '+227 90 99 88 77',
    monthlyFee: 40000,
    paidAmount: 0,
    paymentStatus: 'En retard',
    tutoringStatus: 'Arrêté (Défaut de paiement)',
    stopDate: '15 Fév 2026',
    stopReason: '2 mensualités consécutives impayées. Notification remise au tuteur légal.',
    enrollmentDate: '05 Jan 2026',
    syncStatus: 'synced',
    notes: 'Encadrement suspendu temporairement en attente de régularisation financière.',
    agentId: 'agent-2',
    agentName: 'Hadiza Moussa',
    agentRole: 'Agent de Caisse',
  },
  {
    id: 'stu-6',
    matricule: 'CAB-2026-0112',
    fullName: 'Ramatoulaye Hama Sani',
    level: 'Première D',
    stream: 'Lycée',
    subjects: ['SVT', 'Chimie', 'Maths'],
    guardianName: 'Hama Sani',
    guardianPhone: '+227 96 33 22 11',
    monthlyFee: 30000,
    paidAmount: 15000,
    paymentStatus: 'Partiel',
    tutoringStatus: 'Actif',
    enrollmentDate: '22 Jan 2026',
    syncStatus: 'synced',
    notes: 'Solde restant de 15 000 FCFA promis fin du mois.',
    agentId: 'agent-2',
    agentName: 'Hadiza Moussa',
    agentRole: 'Agent de Caisse',
  },
  {
    id: 'stu-7',
    matricule: 'CAB-2026-0128',
    fullName: 'Fati Kader Djermakoye',
    level: 'CM1',
    stream: 'Primaire',
    subjects: ['Français', 'Calcul', 'Histoire-Géo'],
    guardianName: 'Mme Kader Djermakoye',
    guardianPhone: '+227 94 44 55 66',
    monthlyFee: 18000,
    paidAmount: 18000,
    paymentStatus: 'A jour',
    tutoringStatus: 'Arrêté (À la demande)',
    stopDate: '01 Sep 2026',
    stopReason: 'Déménagement familial temporaire vers Dosso. Demande écrite des parents.',
    enrollmentDate: '12 Jan 2026',
    syncStatus: 'synced',
    notes: 'Encadrement clôturé avec quitus à la demande expresse de la famille.',
    agentId: 'agent-4',
    agentName: 'Fatima Salifou',
    agentRole: 'Secrétaire d\'Accueil',
  },
  {
    id: 'stu-8',
    matricule: 'CAB-2026-0145',
    fullName: 'Mariama Seydou Djibo',
    level: 'CM1 (Prépa CFEPD)',
    stream: 'Primaire',
    subjects: ['Français', 'Calcul & Problèmes'],
    guardianName: 'Seydou Djibo',
    guardianPhone: '+227 92 11 22 33',
    monthlyFee: 18000,
    paidAmount: 15000,
    paymentStatus: 'Partiel',
    tutoringStatus: 'Actif',
    enrollmentDate: 'Aujourd\'hui',
    syncStatus: 'synced',
    notes: 'Nouvelle inscription enregistrée.',
    agentId: 'agent-1',
    agentName: 'M. Lawali B.',
    agentRole: 'Administrateur Principal',
  },
];

export const SEED_PAYMENTS: PaymentReceipt[] = [
  {
    id: 'pay-1',
    receiptNumber: 'REC-2026-0941',
    studentId: 'stu-3',
    studentName: 'Abdoulaye Garba Souley (Terminale D)',
    category: 'Scolarité Mensuelle',
    amount: 35000,
    paymentMethod: 'Airtel Money',
    paymentDate: '29/09/2026 à 10:45',
    cashierName: 'Hadiza Moussa (Caisse Niamey)',
    status: 'Validé',
    syncStatus: 'synced',
    notes: 'Mois de Septembre 2026 - Réf Transaction Airtel: AM-90234812',
    agentId: 'agent-2',
    agentName: 'Hadiza Moussa',
    agentRole: 'Agent de Caisse',
  },
  {
    id: 'pay-2',
    receiptNumber: 'REC-2026-0940',
    studentId: 'stu-1',
    studentName: 'Hadiza Moussa Oumarou (CM2)',
    category: 'Scolarité Mensuelle',
    amount: 20000,
    paymentMethod: 'Espèces',
    paymentDate: '29/09/2026 à 09:30',
    cashierName: 'Hadiza Moussa (Caisse Niamey)',
    status: 'Validé',
    syncStatus: 'synced',
    notes: 'Paiement espèces direct au guichet central Plateau.',
    agentId: 'agent-2',
    agentName: 'Hadiza Moussa',
    agentRole: 'Agent de Caisse',
  },
  {
    id: 'pay-3',
    receiptNumber: 'REC-2026-0939',
    studentName: 'Soumana Mamane (Candidat Concours Police)',
    category: 'Frais Concours',
    amount: 75000,
    paymentMethod: 'Moov Flooz',
    paymentDate: '28/09/2026 à 16:20',
    cashierName: 'M. Lawali B.',
    status: 'Validé',
    syncStatus: 'synced',
    notes: 'Pack Prépa Concours Direct Police Nationale (Épreuves écrites & sport).',
    agentId: 'agent-1',
    agentName: 'M. Lawali B.',
    agentRole: 'Administrateur Principal',
  },
  {
    id: 'pay-4',
    receiptNumber: 'REC-2026-0938',
    studentId: 'stu-4',
    studentName: 'Zeinabou Boubacar Maïga (3ème BEPC)',
    category: 'Scolarité Mensuelle',
    amount: 25000,
    paymentMethod: 'Al Izza / Nita Transfert',
    paymentDate: '28/09/2026 à 11:15',
    cashierName: 'Hadiza Moussa (Caisse Niamey)',
    status: 'Validé',
    syncStatus: 'synced',
    notes: 'Code Al Izza: ALZ-5582910',
    agentId: 'agent-2',
    agentName: 'Hadiza Moussa',
    agentRole: 'Agent de Caisse',
  },
  {
    id: 'pay-5',
    receiptNumber: 'REC-2026-0937',
    studentId: 'stu-8',
    studentName: 'Mariama Seydou Djibo (CM1)',
    category: 'Inscription',
    amount: 15000,
    paymentMethod: 'Espèces',
    paymentDate: '27/09/2026 à 10:15',
    cashierName: 'M. Lawali B.',
    status: 'Validé',
    syncStatus: 'synced',
    notes: 'Frais d\'inscription et dossier administratif.',
    agentId: 'agent-1',
    agentName: 'M. Lawali B.',
    agentRole: 'Administrateur Principal',
  },
];

export const SEED_EXAMS: ExamApplication[] = [
  {
    id: 'ex-1',
    dossierNumber: 'CNR-2026-019',
    candidateName: 'Soumana Mamane Harouna',
    examType: 'Police Nationale',
    examBatch: 'Session 2026 - Corps des Inspecteurs & Officiers',
    requiredPieces: [
      'Extrait d\'acte de naissance légalisé',
      'Certificat de nationalité nigérienne',
      'Casier judiciaire (Bulletin N°3)',
      'Diplôme du Baccalauréat / Licence légalisé',
      'Certificat médical d\'aptitude & Toise (1m68 min)',
      '4 Photos d\'identité récentes',
    ],
    submittedPieces: [
      'Extrait d\'acte de naissance légalisé',
      'Certificat de nationalité nigérienne',
      'Diplôme du Baccalauréat / Licence légalisé',
      '4 Photos d\'identité récentes',
    ],
    status: 'Pièces manquantes',
    contactPhone: '+227 96 11 00 22',
    submissionDate: '24 Fév 2026',
    syncStatus: 'synced',
    agentId: 'agent-3',
    agentName: 'Prof. Ousmane Adamou',
    agentRole: 'Responsable Pédagogique',
  },
  {
    id: 'ex-2',
    dossierNumber: 'CNR-2026-020',
    candidateName: 'Balkissa Ide Saley',
    studentId: 'stu-3',
    examType: 'ENA / ENAM',
    examBatch: 'Concours Direct Section Régie Financière & Douanes',
    requiredPieces: [
      'Extrait d\'acte de naissance légalisé',
      'Certificat de nationalité nigérienne',
      'Casier judiciaire',
      'Diplôme de Licence / Maîtrise',
      'Reçu de versement des frais de dossier',
    ],
    submittedPieces: [
      'Extrait d\'acte de naissance légalisé',
      'Certificat de nationalité nigérienne',
      'Casier judiciaire',
      'Diplôme de Licence / Maîtrise',
      'Reçu de versement des frais de dossier',
    ],
    status: 'Validé',
    contactPhone: '+227 90 44 77 11',
    submissionDate: '26 Fév 2026',
    syncStatus: 'synced',
    agentId: 'agent-1',
    agentName: 'M. Lawali B.',
    agentRole: 'Administrateur Principal',
  },
  {
    id: 'ex-3',
    dossierNumber: 'CNR-2026-021',
    candidateName: 'Hamidou Boureima',
    examType: 'Santé Publique (ENSP)',
    examBatch: 'Concours d\'Entrée École Nationale de Santé Publique',
    requiredPieces: [
      'Extrait de naissance',
      'Certificat de nationalité',
      'BEPC ou Baccalauréat',
      'Certificat de visite médicale',
    ],
    submittedPieces: [
      'Extrait de naissance',
      'Certificat de nationalité',
      'BEPC ou Baccalauréat',
    ],
    status: 'Pièces manquantes',
    contactPhone: '+227 97 88 99 00',
    submissionDate: '27 Fév 2026',
    syncStatus: 'synced',
    agentId: 'agent-3',
    agentName: 'Prof. Ousmane Adamou',
    agentRole: 'Responsable Pédagogique',
  },
  {
    id: 'ex-4',
    dossierNumber: 'CNR-2026-022',
    candidateName: 'Moussa Doudou Abdoulkarim',
    examType: 'Garde Nationale (GNN)',
    examBatch: 'Recrutement Élèves Sous-Officiers GNN 2026',
    requiredPieces: [
      'Acte de naissance légalisé',
      'Certificat de nationalité',
      'Casier judiciaire',
      'Certificat de toise',
    ],
    submittedPieces: [
      'Acte de naissance légalisé',
      'Certificat de nationalité',
      'Casier judiciaire',
      'Certificat de toise',
    ],
    status: 'Validé',
    contactPhone: '+227 91 22 33 44',
    submissionDate: 'Aujourd\'hui · 08:30',
    syncStatus: 'synced',
    agentId: 'agent-4',
    agentName: 'Fatima Salifou',
    agentRole: 'Secrétaire d\'Accueil',
  },
];

export const SEED_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-1',
    sku: 'ANN-BAC-D-26',
    name: 'Annales Officielles Baccalauréat Série D Niger (Maths, PC, SVT 2018-2025)',
    category: 'Manuels & Annales',
    unitPrice: 6500,
    stockQuantity: 42,
    minThreshold: 10,
    syncStatus: 'synced',
    supplier: 'Éditions Pédagogiques du Niger',
  },
  {
    id: 'inv-2',
    sku: 'ANN-BEPC-26',
    name: 'Guide Réussite BEPC Niger avec Corrigés Types & Barèmes Officiels',
    category: 'Manuels & Annales',
    unitPrice: 5000,
    stockQuantity: 28,
    minThreshold: 8,
    syncStatus: 'synced',
    supplier: 'Éditions Scolaires Niamey',
  },
  {
    id: 'inv-3',
    sku: 'MAN-CFEPD-01',
    name: 'Recueil Problèmes de Calcul & Dictées Préparation CFEPD (CM2)',
    category: 'Manuels & Annales',
    unitPrice: 3500,
    stockQuantity: 19,
    minThreshold: 10,
    syncStatus: 'synced',
    supplier: 'Imprimerie Nationale du Niger',
  },
  {
    id: 'inv-4',
    sku: 'FOU-CALC-FX',
    name: 'Calculatrice Scientifique Casio FX-991ES Plus (Conforme Bac & Supérieur)',
    category: 'Outils & Géométrie',
    unitPrice: 16500,
    stockQuantity: 5,
    minThreshold: 12,
    syncStatus: 'synced',
    supplier: 'Bureautique Niger SARL',
  },
  {
    id: 'inv-5',
    sku: 'FOU-UNIF-01',
    name: 'Polo Officiel Cab-Appuis Niamey - Logo Brodé (Tailles Enfant & Adulte)',
    category: 'Tenues & Blasons',
    unitPrice: 7500,
    stockQuantity: 34,
    minThreshold: 15,
    syncStatus: 'synced',
    supplier: 'Atelier Textile Wadata',
  },
  {
    id: 'inv-6',
    sku: 'FOU-CAH-01',
    name: 'Paquet 5 Cahiers 200 pages Grand Format Quadrillé (Scolarité Niger)',
    category: 'Cahiers & Stylos',
    unitPrice: 4000,
    stockQuantity: 60,
    minThreshold: 25,
    syncStatus: 'synced',
    supplier: 'Grossiste Papeterie Grand Marché Niamey',
  },
];

export const SEED_SUPPLY_SALES: SupplySale[] = [
  {
    id: 'sale-1',
    saleNumber: 'VNT-2026-0045',
    customerName: 'Abdoulaye Garba Souley',
    studentId: 'stu-3',
    items: [
      { itemId: 'inv-1', itemName: 'Annales Bac Série D Niger', quantity: 1, unitPrice: 6500, total: 6500 },
      { itemId: 'inv-4', itemName: 'Calculatrice Casio FX-991', quantity: 1, unitPrice: 16500, total: 16500 },
    ],
    totalAmount: 23000,
    paymentMethod: 'Espèces',
    saleDate: '28 Fév 2026',
    syncStatus: 'synced',
    agentId: 'agent-2',
    agentName: 'Hadiza Moussa',
    agentRole: 'Agent de Caisse',
    agentAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'sale-2',
    saleNumber: 'VNT-2026-0046',
    customerName: 'Hadiza Moussa Oumarou',
    studentId: 'stu-1',
    items: [
      { itemId: 'inv-3', itemName: 'Recueil Problèmes CFEPD (CM2)', quantity: 1, unitPrice: 3500, total: 3500 },
      { itemId: 'inv-6', itemName: 'Paquet 5 Cahiers 200p', quantity: 2, unitPrice: 4000, total: 8000 },
    ],
    totalAmount: 11500,
    paymentMethod: 'Espèces',
    saleDate: '01 Sep 2026',
    syncStatus: 'synced',
    agentId: 'agent-2',
    agentName: 'Hadiza Moussa',
    agentRole: 'Agent de Caisse',
    agentAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
];

export const SEED_OPERATIONS: OperationItem[] = [
  {
    id: 'op-1',
    type: 'paiement',
    title: 'Règlement Scolarité Mensuelle',
    subtitle: 'Élève : Abdoulaye Garba (Terminale D) · Reçu REC-2026-0941',
    referenceId: 'REC-2026-0941',
    studentId: 'stu-3',
    amount: 35000,
    timestamp: '10:45',
    syncStatus: 'synced',
    metaBadge: 'Airtel Money',
    agentId: 'agent-2',
    agentName: 'Hadiza Moussa',
    agentRole: 'Agent de Caisse',
  },
  {
    id: 'op-2',
    type: 'inscription',
    title: 'Nouvelle Inscription Primaire',
    subtitle: 'Mariama Seydou Djibo · CM1 (Prépa CFEPD)',
    referenceId: 'CAB-2026-0145',
    studentId: 'stu-8',
    amount: 15000,
    timestamp: '10:15',
    syncStatus: 'synced',
    metaBadge: 'Primaire',
    agentId: 'agent-1',
    agentName: 'M. Lawali B.',
    agentRole: 'Administrateur Principal',
  },
  {
    id: 'op-3',
    type: 'concours',
    title: 'Candidature Garde Nationale (GNN)',
    subtitle: 'Moussa Doudou Abdoulkarim · Dossier CNR-2026-022 complet',
    referenceId: 'CNR-2026-022',
    timestamp: '08:30',
    syncStatus: 'synced',
    metaBadge: 'GNN Niger',
    agentId: 'agent-4',
    agentName: 'Fatima Salifou',
    agentRole: 'Secrétaire d\'Accueil',
  },
  {
    id: 'op-4',
    type: 'paiement',
    title: 'Pack Prépa Concours Police Nationale',
    subtitle: 'Soumana Mamane · Reçu REC-2026-0939',
    referenceId: 'REC-2026-0939',
    amount: 75000,
    timestamp: 'Hier',
    syncStatus: 'synced',
    metaBadge: 'Moov Flooz',
    agentId: 'agent-1',
    agentName: 'M. Lawali B.',
    agentRole: 'Administrateur Principal',
  },
  {
    id: 'op-5',
    type: 'paiement',
    title: 'Scolarité Primaire CM2',
    subtitle: 'Hadiza Moussa Oumarou · Reçu REC-2026-0940',
    referenceId: 'REC-2026-0940',
    studentId: 'stu-1',
    amount: 20000,
    timestamp: '09:30',
    syncStatus: 'synced',
    metaBadge: 'Espèces',
    agentId: 'agent-2',
    agentName: 'Hadiza Moussa',
    agentRole: 'Agent de Caisse',
  },
];

export const SEED_ALERTS: PriorityAlert[] = [
  {
    id: 'alt-1',
    pillar: 'paiement',
    title: '14 Échéances en retard de scolarité (Niamey)',
    description: 'Montant cumulé de 385 000 FCFA à recouvrer pour le cycle en cours.',
    count: 14,
    urgency: 'critique',
    actionLabel: 'Lancer les relances SMS/WhatsApp',
    actionKey: 'relances',
  },
  {
    id: 'alt-2',
    pillar: 'concours',
    title: '6 Dossiers Concours Police & Gendarmerie incomplets',
    description: 'Casier judiciaire du Tribunal de Niamey et certificat de toise requis sous 5 jours.',
    count: 6,
    urgency: 'critique',
    actionLabel: 'Vérifier les pièces',
    actionKey: 'pieces',
  },
  {
    id: 'alt-3',
    pillar: 'stock',
    title: 'Calculatrices scientifiques en seuil critique',
    description: 'Seulement 5 calculatrices FX-991 disponibles avant les épreuves du Baccalauréat.',
    count: 1,
    urgency: 'attention',
    actionLabel: 'Bon de commande fournisseur',
    actionKey: 'reassort',
  },
  {
    id: 'alt-4',
    pillar: 'inscription',
    title: 'Arrêts d\'encadrement & impayés en attente de régularisation',
    description: 'Mahamadou Issoufou Salifou (Terminale C) suspendu pour impayés. Relance tuteur effectuée.',
    count: 2,
    urgency: 'attention',
    actionLabel: 'Consulter le registre des arrêts',
    actionKey: 'suspensions',
  },
];

/**
 * Exécute la migration complète et initiale vers Firestore.
 * Transfère SANS AUCUNE EXCEPTION toutes les données vers les collections Firestore.
 */
export async function seedInitialFirestoreData(force = false): Promise<{ success: boolean; count: number }> {
  try {
    if (!force) {
      const studentsSnap = await getDocs(collection(db, COLLECTIONS.STUDENTS)).catch(() => null);
      if (studentsSnap && !studentsSnap.empty) {
        return { success: true, count: studentsSnap.size }; // Already initialized
      }
    }

    console.log('⚡ Initializing Firestore with complete seed dataset in parallel...');

    let totalDocs = 0;

    await Promise.all([
      // 1. Agents
      ...SEED_AGENTS.map((agent) =>
        setDoc(doc(db, COLLECTIONS.AGENTS, agent.id), sanitizeForFirestore(agent), { merge: true }).then(() => { totalDocs++; })
      ),
      // 2. Students
      ...SEED_STUDENTS.map((student) =>
        setDoc(doc(db, COLLECTIONS.STUDENTS, student.id), sanitizeForFirestore(student), { merge: true }).then(() => { totalDocs++; })
      ),
      // 3. Payments
      ...SEED_PAYMENTS.map((payment) =>
        setDoc(doc(db, COLLECTIONS.PAYMENTS, payment.id), sanitizeForFirestore(payment), { merge: true }).then(() => { totalDocs++; })
      ),
      // 4. Exams
      ...SEED_EXAMS.map((exam) =>
        setDoc(doc(db, COLLECTIONS.EXAMS, exam.id), sanitizeForFirestore(exam), { merge: true }).then(() => { totalDocs++; })
      ),
      // 4.1 Tutors
      ...SEED_TUTORS.map((tutor) =>
        setDoc(doc(db, COLLECTIONS.TUTORS, tutor.id), sanitizeForFirestore(tutor), { merge: true }).then(() => { totalDocs++; })
      ),
      // 5. Inventory
      ...SEED_INVENTORY.map((item) =>
        setDoc(doc(db, COLLECTIONS.INVENTORY, item.id), sanitizeForFirestore(item), { merge: true }).then(() => { totalDocs++; })
      ),
      // 6. Supply Sales
      ...SEED_SUPPLY_SALES.map((sale) =>
        setDoc(doc(db, COLLECTIONS.SUPPLY_SALES, sale.id), sanitizeForFirestore(sale), { merge: true }).then(() => { totalDocs++; })
      ),
      // 7. Operations
      ...SEED_OPERATIONS.map((op) =>
        setDoc(doc(db, COLLECTIONS.OPERATIONS, op.id), sanitizeForFirestore(op), { merge: true }).then(() => { totalDocs++; })
      ),
      // 8. Alerts
      ...SEED_ALERTS.map((alert) =>
        setDoc(doc(db, COLLECTIONS.ALERTS, alert.id), sanitizeForFirestore(alert), { merge: true }).then(() => { totalDocs++; })
      ),
      // 9. Meta / Settings
      setDoc(
        doc(db, COLLECTIONS.SETTINGS, 'migration_meta'),
        sanitizeForFirestore({
          migratedAt: new Date().toISOString(),
          version: '1.0.0',
          platform: 'Google Firebase Cloud Firestore',
          status: 'SUCCESS',
        }),
        { merge: true }
      ),
    ]);

    console.log(`✅ Firestore seeding successfully completed! (${totalDocs} documents written)`);
    return { success: true, count: totalDocs };
  } catch (err) {
    handleFirestoreError(err, OperationType.WRITE, 'migration_seed');
    return { success: false, count: 0 };
  }
}
